#!/usr/bin/env python
#------------------------------------------------------------------------------
#   MUDserver.py
#   
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain a
#   copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#------------------------------------------------------------------------------

"""
Chat Room Demo for Miniboa.
"""

from miniboa import TelnetServer

import Engine

IDLE_TIMEOUT = 300
CLIENT_LIST = []
SERVER_RUN = True
CLIENT_DATA = {}


def on_connect(client):
    """
    Sample on_connect function.
    Handles new connections.
    """
    clientDataLoc = str(client.addrport())
    print "++ Opened connection to %s" % client.addrport()
    #broadcast('%s connected.\n' % client.addrport() )
    CLIENT_LIST.append(client)
    CLIENT_DATA[clientDataLoc] = {'name':'none', 'prompt':'>>'}
    client.send("\nWelcome to the MUD!\nPlease tell us your name.\n%s" % str(CLIENT_DATA[clientDataLoc]['prompt']))


def on_disconnect(client):
    """
    Sample on_disconnect function.
    Handles lost connections.
    """
    print "-- Lost connection to %s" % client.addrport()
    CLIENT_LIST.remove(client)
    #broadcast('%s leaves the conversation.\n' % client.addrport() )


def kick_idle():
    """
    Looks for idle clients and disconnects them by setting active to False.
    """
    ## Who hasn't been typing?
    for client in CLIENT_LIST:
        if client.idle() > IDLE_TIMEOUT:
            print('-- Kicking idle lobby client from %s' % client.addrport())
            client.active = False


def broadcast(msg):
    """
    Send msg to every client.
    """
    for client in CLIENT_LIST:
        client.send(msg)




 


#------------------------------------------------------------------------------
#       Main
#------------------------------------------------------------------------------

if __name__ == '__main__':

    ## Simple chat server to demonstrate connection handling via the
    ## async and telnet modules.

    ## Create a telnet server with a port, address,
    ## a function to call with new connections
    ## and one to call with lost connections.

    telnet_server = TelnetServer(
        port=7777,
        address='',
        on_connect=on_connect,
        on_disconnect=on_disconnect,
        timeout = .05
        )

    print(">> Listening for connections on port %d.  CTRL-C to break."
        % telnet_server.port)

    ## Server Loop
    while SERVER_RUN:
        telnet_server.poll()        ## Send, Recv, and look for new connections
        kick_idle()                 ## Check for idle clients
        engineState = Engine.process_clients(SERVER_RUN, CLIENT_LIST, CLIENT_DATA)           ## Check for client input, saving any state changes generated by the engine to 'engineState'

        if engineState == "shutdown":
            SERVER_RUN == False

    print(">> Server shutdown.")
